Provide sha256 checksum with file updates
s3tools/s3cmd pull request #1353
Opened 2023-11-13 09:18 UTC by eullerborges

Fixes #1177. I tried `Content-MD5` as well, but that was more involved.

2023-12-05 02:58 UTC, rampageservices requested changes
Typo needs fixing.
Suggest improvement for readability.

2023-12-05 02:58 UTC, rampageservices commented on S3/S3.py
> +        # Provide the checksum with teh request. This is important for buckets that have
"the" is spelled incorrectly here, shown as "teh". Minor typo.

2023-12-05 02:58 UTC, rampageservices commented on S3/S3.py
> +        headers['x-amz-checksum-sha256'] = base64.b64encode(sha256_hash.digest()).decode()
`base64.b64encode(sha256_hash.digest()).decode()`
Can this line be broken down? It is doing a lot all at once. It is hard for readability.
Perhaps we  canpull out the digest operation into a separate sha256_hash_digest variable?
Or maybe this functionality can be separated into a new function in S3/Crypto.py

I know this exact line is recommended online in tutorials but is in my opinion hard to read.
See: https://debugpointer.com/python/sha256-to-base64-python

2025-01-19 11:14 UTC, snosratiershad commented on S3/S3.py
> +        headers['x-amz-checksum-sha256'] = base64.b64encode(sha256_hash.digest()).decode()
As someone could use s3cmd as library this line can override the header potentially comes with request argument's headers attribute. I think it's better to check if it currently has values:
```python
if not headers.get("x-amz-checksum-sha256"):
    headers['x-amz-checksum-sha256'] = sha256_hash_to_base64(sha256_hash)
```

Also in this module encodestring (which imported above as an alias of encodebytes when available) is the function used for base64 encoding.
I think you can use:
```python
sha256_hash_digest_b64 = encodestring(sha256_hash_digest).strip().decode()
```
to align with other usecases.

2025-01-19 11:17 UTC, snosratiershad commented
I think we can close this PR as #1393 has completed this reviews.

2025-01-27 02:58 UTC, fviard commented
Closing as suggested, to be replaced by #1393

2025-01-27 02:58 UTC, closed without merging

2025-04-22 17:44 UTC, eullerborges commented
Sorry for not coming back to this, I've been away from GitHub for a while. I'm glad this was picked up and merged in. Thank you!